"""
Prepares training data for Needle 3 LoRA Fine-Tuning.
Converts the exact 1,650 training examples generated by build_finetune_dataset
into Needle's native {"tools": [...], "query": "...", "answers": [...]} format.
"""

import json
import os
import sys
from typing import Literal

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import needle
from mara.argument_heads import ROOMS, DEVICES, ACTIONS
from research.finetune_tools import build_finetune_dataset
from research.reextract_stateless_fair_failures import FAIR_TOOLS

agent = needle.Needle(tools=FAIR_TOOLS)
TOOL_SCHEMAS = json.loads(agent._tools_json.decode("utf-8"))


def prepare_needle_data():
    raw_samples = build_finetune_dataset(1500)
    print(f"Loaded {len(raw_samples)} raw training samples from Mara dataset generator.")

    needle_examples = []
    for s in raw_samples:
        q = s["query"]
        t_idx = s["tool_idx"]

        answers = []
        if t_idx == 0:  # set_lights
            room = ROOMS[s["room_idx"]]
            b = int(s.get("target_num", "100" if s.get("is_on", True) else "0"))
            answers = [{"name": "set_lights", "arguments": {"room": room, "brightness": b}}]
        elif t_idx == 1:  # set_thermostat
            temp = float(s["target_num"])
            answers = [{"name": "set_thermostat", "arguments": {"temperature_c": temp}}]
        elif t_idx == 2:  # control_device
            dev = DEVICES[s["device_idx"]]
            act = ACTIONS[s["action_idx"]]
            answers = [{"name": "control_device", "arguments": {"device": dev, "action": act}}]
        elif t_idx == 3:  # lock_door
            locked = (s["lock_idx"] == 0)
            answers = [{"name": "lock_door", "arguments": {"door": "front door", "locked": locked}}]
        elif t_idx == 4:  # none
            answers = []

        needle_examples.append({
            "tools": TOOL_SCHEMAS,
            "query": q,
            "answers": answers,
        })

    out_train = os.path.join(ROOT, "data", "needle_train.jsonl")
    with open(out_train, "w", encoding="utf-8") as f:
        for ex in needle_examples:
            f.write(json.dumps(ex) + "\n")

    print(f"Successfully formatted {len(needle_examples)} examples to: {out_train}")


if __name__ == "__main__":
    prepare_needle_data()
